### ISSUE TITLE
Can not clone recursive submodule

### ISSUE THREAD

**Issue by phongnhhn92** [NVlabs/watch-it-move#3]
Hi, 
Thanks for the code but I can not clone all the submodule in the repo ? Can u fix this ? 

```
git clone --recursive git@github.com:NVlabs/watch-it-move.git
Cloning into 'watch-it-move'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by oraziogallo** [comment]
Hi,
It may be because you haven't configured any ssh identity on your end. You can either do that (add an ssh key to you github account, and set it up on your local machine) or use https instead:

git clone --recursive https://github.com/NVlabs/watch-it-move.git
